name: React.js CI  # Name of the workflow

on: push  # Trigger the workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository  # Step to checkout the repository code
        uses: actions/checkout@v4.2.2  # Use the checkout action version 4.2.2

      - name: Set up Node.js  # Step to set up Node.js environment
        uses: actions/setup-node@v4.2.0  # Use the setup-node action version 4.2.0
        with:
          node-version: '23'  # Specify the Node.js version to use

      - name: Install dependencies  # Step to install Node.js dependencies
        run: npm install  # Install dependencies using npm

      - name: Run lint  # Step to run linting
        run: npm run lint  # Run linting using npm script

      - name: Build project  # Step to build the project
        run: npm run build  # Build the project using npm script

      - name: Upload artifact  # Step to upload the build artifact
        uses: actions/upload-artifact@v4.6.0  # Use the upload-artifact action version 4.6.0
        with:
          name: build  # Name of the artifact
          path: build/  # Path to the build files
