name: Manual Approval Deployment Workflow
  
on:
 push:
   branches:
     - dev

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name: Run tests
       run: |
         echo "Running tests..."
    
 hold:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - name: Manual approval
       uses: trstringer/manual-approval@v1.9.0
       with:
         approvers: 'deepaknagaraj-1997'
         secret: ${{ secrets.GITHUB_TOKEN }}
         minimum-approvals: 1
         issue-title: "Deploying v1.3.5 to prod from staging"
         issue-body: "Please approve or deny the deployment of version v1.3.5."

 deploy:
   needs: hold
   runs-on: ubuntu-latest
   steps:
     - name: Deploy to staging
       run: |
         echo "Deploying to staging..."
         # Add your deployment commands here
